= とてもよいプライバシー =
:doctype: book
:toc:
:author: 合同会社オイコノミカ
:experimental:  

[[introduction]]
== はじめに ==
あなたは、プライバシーを大切にしたいと思いますか？
たとえば人に知られたくないような趣味趣向、奥さんとの内緒話のようなものです。
きっとあなたは、こういった情報を第三者に知られたくないと思います。
もちろん、なにかやましいことでなくてでもです。

秘密にしたいメッセージは、インターネットでやり取りしないのが理想ですが
インターネット全盛の時代にすべてそうするのは非効率です。

そこで役に立つのが暗号技術です。暗号技術を正しく使えば、
信用できないサーバーや公衆無線LANのような必ずしも安全ではない通信経路を経由しても秘密を守ることができます。

このハンドブックでは、PGP(Pretty Good Privacy)という暗号技術によって、
あなたの大切なプライバシーを守る方法を説明します。

:numbered:

== PGP(Pretty Good Privacy) ==

=== PGP(Pretty Good Privacy)とは ===
PGP(Pretty Good Privacy)は、Philip Zimmermannが開発した暗号化ソフトウェアです。
1991年に開発され、今日まで一般的ユーザーから専門的なユーザーまで広く愛好されつづけています。

PGPは、公開鍵暗号方式を採用しており、暗号化・復号するための鍵は、二つにわかれています。

|===
^|鍵の種類 ^| できること

|公開鍵
a|
* 暗号化
* 署名の検証


|秘密鍵
a|
* 復号
* 署名
|===

鍵の名前の通り、公開鍵は他人に公開してよいもので、秘密鍵は他人には秘密にしておくものです。
このように鍵の用途を分けることで、鍵を交換してる間に傍受・盗聴されても大丈夫な仕組みになっています。

仮に公開鍵が悪意のある攻撃者にわたったとしても、秘密のメッセージを解読できたりしません。
もちろん、秘密鍵は、インターネット回線に流さないなど、できる限り慎重に保管する必要があります。

=== 環境構築 ===
本書では、PGPの有名な実装の一つであるGPG(GNU Privacy Guard)を使用します。
あなたの環境に応じて、GPGをインストールしてください。

|===
^|OS ^| ソフトウェア名 ^| リンク

| GNU/Linux
| GnuPG
| https://www.gnupg.org/

| Windows
| Gpg4win
| https://www.gpg4win.org/

| OS X 
| Mac GPG
| https://gpgtools.org/
|===

インストールしたあと、ターミナルで下記のコマンドを実行してください。

--------------------------------------------------
$ gpg --version
--------------------------------------------------

GPGのバージョン番号が表示されていれば、インストールは成功です。

NOTE: `$` は、シェルとの対話を表しています。環境や設定によって異なるものが表示されているでしょう。

[CAUTION]
====
ターミナルの起動方法はOSによって異なります。

* Windowsであれば、 kbd:[⊞ Win + R] → `cmd` → kbd:[Enter] でコマンドプロンプトを起動します。
* OS Xであれば、 kbd:[⌘ Command + スペースバー] → `ターミナル` でターミナルを起動します。
* GNU/Linuxであれば、……すでにご存知でしょう。
====

=== 鍵ペア生成 ===
鍵ペアを生成するために、ターミナルで下記のコマンドを実行してください。

--------------------------------------------------
$ gpg --gen-key
--------------------------------------------------

あとはコマンドの出力にしたがってお好みの設定を選んでください。
本書は、下記の設定を推奨します。

|===
^|設定項目 ^| 推奨設定 ^| 説明

|鍵の種類
|RSA and RSA
|特に理由がなければ、RSA and RSAを選びましょう。

|鍵長
|2048
|鍵長は、2048ビットで十分です。4096ビットを使ったところでlink:https://www.gnupg.org/faq/gnupg-faq.html#no_default_of_rsa4096["大した効果はありませんし、無駄に時間がかかるようになるだけです"]。

|鍵の有効期限
|無期限
|頻繁に公開鍵を交換できない場合は、無期限としておきましょう。もちろん有効期限を設定することは悪いことではありません。

|名前
|アルファベットの名前(例: Taro Yamada)
|-

|メールアドレス
|会社が発行した oikonomika.jp ドメインのメールアドレスを指定
|-

|コメント
|空欄
|コメントは、必要ありません。
|===

鍵ペアの生成に成功したら、フィンガープリントが表示されます。
フィンガープリントの値は、`Key fingerprint` もしくは `指紋` という欄に出力されます。
このフィンガープリントは、名刺を作成するためにも必要なので名刺を作成する担当者に伝えてください。

CAUTION: フィンガープリントは、対面で伝えるようにしてください。悪意のある攻撃者がフィンガープリントを違うものにすり替えてしまった場合、プライバシーを保護できなくなってしまいます。

[[creating-a-revocation-key]]
=== 失効証明書の作成 ===
失効証明書を作成するために、ターミナルで下記のコマンドを実行してください。

--------------------------------------------------
$ gpg --output revoke.asc --gen-revoke
--------------------------------------------------

作成理由(もしくはreason for the revocation)を選択する必要がありますが、
`0 = No reason specified` を選択してください。また、説明(description)も空欄で大丈夫です。

失効証明書のファイルは、`--output` 引数で指定した `revoke.asc` というファイル名でカレントディレクトリに作成されます。

=== 鍵・失効証明書のバックアップ ===
秘密鍵をファイルとしてエクスポートするために、ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --armor --export-secret-keys _あなたのメールアドレス_ > secret.asc
--------------------------------------------------

秘密鍵のファイルは、出力先で指定した `secret.asc` というファイル名でカレントディレクトリに作成されます。
<<creating-a-revocation-key>>で作成した `revoke.asc` と一緒にバックアップしておきましょう。

フラッシュメモリは、長期保存には向かないのでバックアップ用のハードディスクドライブにバックアップするなどしてください。

=== 公開鍵のエクスポート ===
公開鍵を交換するために、まずファイルとしてエクスポートします。
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --armor --export _あなたのメールアドレス_ > pub.asc
--------------------------------------------------

カレントディレクトリに、公開鍵ファイル `pub.asc` が作成されるのでこのファイルを通信したい相手に渡しましょう。

=== 公開鍵の交換、フィンガープリント確認 ===
通信したい相手から公開鍵を受け取ったら、まずは鍵束にインポートしましょう。
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --import _相手の公開鍵ファイル名_
--------------------------------------------------

インポートした公開鍵のフィンガープリントを確認するために、
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --fingerprint _相手のメールアドレス_
--------------------------------------------------

公開鍵と相手が一致しており、かつ公開鍵のフィンガープリントが同一であれば、公開鍵への署名をします。
ターミナルで下記のコマンドを実行してください。1行目のコマンドを入力したあとは、対話モードになるので出力にしたがって操作してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --local-user _あなたのメールアドレス_ --edit-key _相手のメールアドレス_
gpg> sign
本当に署名しますか? (y/N) y
gpg> q
変更を保存しますか? (y/N) y
--------------------------------------------------

=== ファイルの署名 ===
ファイルに署名するには、
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --armor --sign _署名するファイル名_
--------------------------------------------------

カレントディレクトリに、署名ファイルが出力されます。

=== ファイルの検証 ===
署名したファイルが正しいかどうか検証するには、
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --verify _検証するファイル名_
--------------------------------------------------

検証結果が出力されます。

=== ファイルの暗号化 ===
ファイルを暗号化するには、
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --armor -r _送信先のメールアドレス_ --encrypt _暗号化するファイル名_ > _出力ファイル名_
--------------------------------------------------

=== ファイルの復号 ===
暗号化されたファイルを復号するには、
ターミナルで下記のコマンドを実行してください。

[subs="quotes"]
--------------------------------------------------
$ gpg --decrypt _復号するファイル名_ > _出力ファイル名_
--------------------------------------------------

=== 紛失・盗難時の対応 ===
万が一、秘密鍵を紛失してしまったり、盗難されてしまった場合は、
公開鍵を配った全員へ<<creating-a-revocation-key>>で作成した失効証明書を配布してください。
また新しい鍵ペアを作成して新しい公開鍵を配布してください。
フィンガープリントも変わるので、名刺は破棄してください。

== Mailvelopeによる安全なメール環境作り ==
=== インストール ===
=== 設定 ===
=== メールの署名・暗号化 ===

:numbered!:

== 最後に ==

== 参考文献 ==

[bibliography]
- 結城浩『暗号技術入門 第3版　秘密の国のアリス』 SBクリエイティブ、ISBN 978-4797382228 (2008)。
- 村川猛彦「1分でわかるPGP」(http://www.wakayama-u.ac.jp/~takehiko/pgp.html) 2018年7月26日アクセス。
- 「GnuPG - Arch Wiki」(https://wiki.archlinux.jp/index.php/GnuPG) 2018年7月26日アクセス。
