= とてもよいプライバシー =
:doctype: book
:sectnums:
:toc:
:author: 合同会社オイコノミカ
:experimental:  

== 概要 ==
あなたは、プライバシーを大切にしたいと思いますか？
たとえば人に知られたくないような趣味趣向、奥さんとの内緒話のようなものです。
きっとあなたは、こういった情報を第三者に知られたくないと思います。
もちろん、なにかやましいことでなくてでもです。

秘密にしたいメッセージは、インターネットでやり取りしないのが理想ですが
インターネット全盛の時代にすべてそうするのは非効率です。

そこで役に立つのが暗号技術です。暗号技術を正しく使えば、
信用できないサーバーや公衆無線LANのような必ずしも安全ではない通信経路を経由しても秘密を守ることができます。

このハンドブックでは、PGP(Pretty Good Privacy)という暗号技術によって、
あなたの大切なプライバシーを守る方法を説明します。

=== 環境構築 ===
本書では、PGPの有名な実装の一つであるGPG(GNU Privacy Guard)を使用します。
あなたの環境に応じて、GPGをインストールしてください。

|===
^|OS ^| ソフトウェア名 ^| リンク

| GNU/Linux
| GnuPG
| https://www.gnupg.org/

| Windows
| Gpg4win
| https://www.gpg4win.org/

| OS X 
| Mac GPG
| https://gpgtools.org/
|===

インストールしたあと、ターミナルで下記のコマンドを実行してください。

--------------------------------------------------
$ gpg --version
--------------------------------------------------

GPGのバージョン番号が表示されていれば、インストールは成功です。

NOTE: `$` は、シェルとの対話を表しています。環境や設定によって異なるものが表示されているでしょう。

CAUTION: ターミナルの操作法はOSによって異なります。Windowsであれば、 kbd:[⊞ Win + R] → `cmd` → kbd:[Enter] でコマンドプロンプトを表示します。

=== 鍵ペア生成 ===
鍵ペアを生成するために、ターミナルで下記のコマンドを実行してください。

--------------------------------------------------
$ gpg --gen-key
--------------------------------------------------

あとはコマンドの出力にしたがってお好みの設定を選んでください。
本書は、下記の設定を推奨します。

|===
^|設定項目 ^| 推奨設定 ^| 説明

|鍵の種類
|RSA and RSA
|特に理由がなければ、RSA and RSAを選びましょう。

|鍵長
|2048
|鍵長は、2048ビットで十分です。4096ビットを使ったところでlink:https://www.gnupg.org/faq/gnupg-faq.html#no_default_of_rsa4096["大した効果はありませんし、無駄に時間がかかるようになるだけです"]。

|鍵の有効期限
|無期限
|頻繁に公開鍵を交換できない場合は、無期限としておきましょう。もちろん有効期限を設定することは悪いことではありません。

|名前
|アルファベットの名前(例: Taro Yamada)
|-

|メールアドレス
|会社が発行した oikonomika.jp ドメインのメールアドレスを指定
|-

|コメント
|空欄
|コメントは、必要ありません。
|===

鍵ペアの生成に成功したら、フィンガープリントが表示されます。
フィンガープリントの値は、`Key fingerprint` もしくは `指紋` という欄に出力されます。
このフィンガープリントは、名刺を作成するためにも必要なので名刺を作成する担当者に伝えてください。

CAUTION: フィンガープリントは、対面で伝えるようにしてください。悪意のある攻撃者がフィンガープリントを違うものにすり替えてしまった場合、プライバシーを保護できなくなってしまいます。

=== 失効証明書の作成 ===
=== 鍵・失効証明書のバックアップ ===
=== 公開鍵の交換、フィンガープリント確認 ===
=== ファイルの署名、検証 ===
=== ファイルの暗号化、復号 ===
=== メッセージの暗号化、復号 ===
=== 紛失・盗難時の対応 ===

== Mailvelopeによる安全なメール環境作り ==
=== インストール ===
=== 設定 ===
=== メールの署名・暗号化 ===

== 最後に ==

== 参考文献 ==

[bibliography]
- 結城浩『暗号技術入門 第3版　秘密の国のアリス』 SBクリエイティブ、ISBN 978-4797382228 (2008)。
- 村川猛彦「1分でわかるPGP」(http://www.wakayama-u.ac.jp/~takehiko/pgp.html) 2018年7月26日アクセス。
- 「GnuPG - Arch Wiki」(https://wiki.archlinux.jp/index.php/GnuPG) 2018年7月26日アクセス。
